---
- name: Kube repo
  copy: src=files/kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo

- name: Kube packages
  yum:
    name: "{{ kube_packages }}"
    state: present
    disable_excludes: kubernetes

- name: Kubelet service enabled 
  systemd:
    name: kubelet
    enabled: yes

# CentOS 7 have reported issues with traffic being routed incorrectly due to iptables being bypassed
- name: Kube bridge param
  sysctl:
    name: "{{ item }}" 
    value: 1
    sysctl_file: /etc/sysctl.d/k8s.conf
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
