---
- name: Check if cluster is already initiated
  register: kubeadm_status
  ignore_errors: True
  command: kubeadm init --dry-run

- name: Init cluster
  when: kubeadm_status.rc == 0
  shell: |
    kubeadm init --pod-network-cidr {{ pod_network_cidr }} \
                 --apiserver-advertise-address {{ ansible_default_ipv4.address }}

- name: Create kubectl config directory
  file:
    path: "~/.kube/"
    state: directory

- name: Copy config to kube directory 
  copy:
    src: "{{ kubeadmin_config }}"
    dest: "~/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
    remote_src: yes

- name: Set Flannel as CNI
  command: kubectl apply -f {{ kube_cni }} 

- name: Get node state
  register: node_state
  command: kubectl get nodes

- name: Enable schedule pods on the master
  when: '"NotReady" in node_state.stdout_lines'
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
