---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest 

- name: Install required system packages
  yum: name={{ system_packages }} state=present

- name: Python required packages
  pip:
    name: '{{ item }}'
    extra_args: --ignore-installed ipaddress
  loop:
    - kubernetes
    - openshift 
